{{- if .Values.config.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lens-template-service-python.fullname" . }}
  labels:
    {{- include "lens-template-service-python.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
