{{- if .Values.secret.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lens-template-service-python.fullname" . }}
  labels:
    {{- include "lens-template-service-python.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
